apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  domain: apps.{{ cluster }}.{{ domain }}
  replicas: {{ replicas }}
  endpointPublishingStrategy:
    type: HostNetwork
{% if role == 'master' %}
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/master: ""
{% endif %}
