language: python
dist: bionic
notifications:
  irc:
    channels:
    - chat.freenode.net#kcli
    on_success: change
    on_failure: always
sudo: required
python:
- 3.6
before_install:
- pip install pep8 twine misspellings stdeb
- pip install setuptools --upgrade
script:
- find . -name \*.py -exec pep8 --ignore=E402,W504 --max-line-length=120 {} +
- find . -name '*.py' | misspellings -f -
- echo $TRAVIS_COMMIT > extras/git_version
- docker build -t karmab/kcli -f extras/alpine .
- docker run -it --rm karmab/kcli
- rm extras/git_version
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ] ; then
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ; docker push karmab/kcli:latest
  ; fi
- if [ "$TRAVIS_TAG" != "" ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  ; docker push karmab/kcli:$TRAVIS_TAG ; fi
- "./pypi.sh"
