language: python
notifications:
  email:
    recipients:
      - karimboumedhel@gmail.com
sudo: required

python:
- 2.7

before_install:
- pip install pep8
- pip install misspellings
- docker build -t karmab/kcli -f extras/Dockerfile/travis .

script:
- find . -name \*.py -exec pep8 --ignore=E402 --max-line-length=120 {} +
- find . -name '*.py' | misspellings -f -
- docker run -it --rm karmab/kcli 
- docker build -t karmab/kcli -f extras/Dockerfile/alpine .

script:
- find . -name \*.py -exec pep8 --ignore=E501,E402 {} +
- find . -name '*.py' | misspellings -f -
- docker run -it --rm karmab/kcli 

#deploy:
#  provider: pypi
#  distributions: sdist
#  skip_cleanup: true
#  user: "karmab"
#  password:
#    secure: "F2gTWXDrOLmf7JglF1mgIdr9imjc0lL/y0K+xDDdcY4yXX9pl/aG8uoS9UhO5IZMsUrgp8xV7XqlYhNyPt61XO8wui52cKZxVfJU1IiYP3PoN382r2iNW4OfrMtzJXcwOoroXRKzZuQpz1HHI5G5EGQPGnlIZHTPBbHBvqyCqlhU7TS3hwPZ4V2bBOjc0l8PToTL9r//8wRIUxhmmHoAMOq7SiAGy/sqQMZn0G8OCU2+B3sncU15chQKb6BpI3ImaL/WL/YHnkLmSThIVFtRu3z2cZAGW49x69aj2cfM65BgJsJa6dJr+cC3SQSQJtWyDsqdHiB43EdgBJqyF3MWS72OY/cMGstr8OaurYqjvySHF6s1SevQD5dmYpmca4Qc6HavfWgB0P1Q1Ai0P8Sl4wgRlI4AmVyY3AHOGYJJVxk5sT+wwUmEq7FmRFFIUtiDV4cDVGwzeLTvfxCtZtZ0aG4fKoCPHyf0eeDfBMNF9eowPmTXa4C0LkSV+B6iSMj+rUEHOd3d/b4UgdsBTikLqdxiKmgoHgx4s2Mf0WZiE/AyVTTaxPVGHuyw8ajVw70xSjyk50eOKqra8yMc/4IPGw05qoprOAt/Qj+JTHdVoWzD0MM8VB92h8Sm17ibZ53dwaU2FHIzEVFDvZtPknII9K5DEAp62hm2yDFwArcFzTY="
#  on:
#    branch: master
