language: python
sudo: required
python:
- 2.7
- 3.3
- 3.4
- 3.5
notifications:
  email: false
before_install:
- pip install pep8
- pip install misspellings

install:
- apt-get -y install python-pip pkg-config libvirt-dev python-dev genisoimage qemu-kvm telnet python-libvirt libvirt-bin
- pip install .

script:
- find . -name \*.py -exec pep8 --ignore=E501,E402 {} +
- find . -name '*.py' | misspellings -f -
- py.test
