apiVersion: batch/v1
kind: Job
metadata:
  name: install-operators
  namespace: kcli-infra
  labels:
    app: kcli
spec:
  backoffLimit: 12
  template:
   spec:
    serviceAccountName: autoapprover
    restartPolicy: OnFailure
    initContainers:
    - name: wait-for-cluster-version
      image: {{ registry }}/karmab/kubectl:latest
      command:
      - "/bin/sh"
      - "-c"
      - |
        #!/bin/sh
        CLUSTER_VERSION=$(kubectl get clusterversion version -o jsonpath='{.status.history[0].state}')
        [ "$CLUSTER_VERSION" == "Completed" ] || exit 1
    containers:
    - name: install-operators
      image: {{ registry }}/karmab/kcli:latest
      command:
      - "/bin/sh"
      - "-c"
      - |
        #!/bin/sh
        echo {{ overrides|base64 }} | base64 -d > ./params.yml
        {% for app in overrides.apps %}
        kcli install app openshift {{ app }} --pf ./params.yml
        {% endfor %}
