apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  defaultNetwork:
    type: OVNKubernetes
    ovnKubernetesConfig:
      mtu: {{ mtu }}
{% if ipsec %}
      ipsecConfig: {}
{% endif %}
{% if ovn_hostrouting or relocate %}
      gatewayConfig:
        routingViaHost: true
{% endif %}
