parameters:
 kubernetes_version: v1.12.0
 domain: cnvlab.gce.sysdeseng.com

custom:
 type: network
 cidr: 10.240.0.0/24
 dhcp: True

kubernetes-the-hard-way:
 type: loadbalancer
 port: 80
 domain: [[ domain ]]
 vms:
  - controller1
  - controller-2
  - controller-3

[% for i in range(0, 2) %]
controller-[[ i ]]:
 template: ubuntu-1804-lts
 flavor: n1-standard-1
 reservedns: true
 sharedkey: true
 disks:
  - size: 200
 nets:
  - name: custom
    ip: 10.240.0.1[[ i ]]
 tags:
  - kubernetes-the-hard-way
  - controller
 files:
  - path: ca-config.json
    origin: ca-config.json
  - origin: ca-csr.json
    path: ca-csr.json
  - origin: admin-csr.json
    path: admin-csr.json
  - origin: instance-csr.json
    path: instance-csr.json
  - origin: kube-controller-manager-csr.json
    path: kube-controller-manager-csr.json
  - origin: kube-proxy-csr.json
    path: kube-proxy-csr.json
  - origin: kube-scheduler-csr.json
    path: kube-scheduler-csr.json
  - origin: kubernetes-csr.json
    path: kubernetes-csr.json 
  - origin: service-account-csr.json
    path: service-account-csr.json
  - origin: encryption-config.yaml
    path: encryption-config.yaml
  - origin: etcd.service
    path: etcd.service
  - origin: launch.sh
    path: launch.sh
[% endfor %]


[% for i in range(0, 2) %]
worker-[[ i ]]:
 template: ubuntu-1804-lts
 flavor: n1-standard-1
 sharedkey: true
 disks:
  - size: 200
 nets:
  - name: custom
    ip: 10.240.0.2[[ i ]]
 tags:
  - kubernetes-the-hard-way
  - controller
[% endfor %]
