- hosts: localhost
  tasks:
    - name: Test kvirt here
      kvirt_vm: 
        host: 192.168.0.6
        name: bobby2
        state: present
        numcpus: 3
        memory: 768
        pool: vms
        template: CentOS-7-x86_64-GenericCloud.qcow2
      register: result
    - debug: var=result 
