parameters:
 nodes: 3
 domain: karmalabs.com
 template: CentOS-7-x86_64-GenericCloud.qcow2
 deploy_app: false

kumaster:
 template: [[ template ]]
 numcpus: 2
 memory: 4096
 reservedns: true
 sharedkey: true
 domain: [[ domain ]]
 nets:
  - default
 disks:
  - size: 50
 pool: default
 files:
  - path: /etc/yum.repos.d/kubernetes.repo
    origin: kubernetes.repo
  - path: /root/kube-flannel.yml
    origin: kube-flannel.yml
  - path: /root/kube-flannel-rbac.yml
    origin: kube-flannel-rbac.yml
 scripts: 
  - pre.sh
  - master.sh
[% if deploy_app %]
  - app.sh
[% endif %]
  - heapster.sh
  - dashboard.sh

[% if nodes > 0 %]
[% for number in range(0, nodes) %]
kunode0[[ number + 1 ]]:
 template: [[ template ]]
 numcpus: 2
 memory: 4096
 reservedns: true
 sharedkey: true
 domain: [[ domain ]]
 nets:
  - default
 disks:
  - size: 50
 pool: default
 files:
  - path: /etc/yum.repos.d/kubernetes.repo
    origin: kubernetes.repo
 scripts: 
  - pre.sh
[% endfor %]
[% endif %]
