minikube:
 template: Fedora-Cloud-Base-26-1.5.x86_64.qcow2
 numcpus: 2
 memory: 6144
 reservedns: true
 nets:
  - default
 disks:
  - size: 10
  - size: 30
 pool: default
 cmds: 
  - yum -y install docker bash-completion
  - systemctl enable docker
  - sed -i "s@# INSECURE_REGISTRY=.*@INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'@" /etc/sysconfig/docker
  - echo -e "DEVS=/dev/vdb\nVG=dockervg" > /etc/sysconfig/docker-storage-setup
  - docker-storage-setup
  - systemctl start docker
  - curl -L https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
  - chmod +x /usr/local/bin/kubectl
  - echo "source <(kubectl completion bash)" >> ~/.bashrc
  - curl -L https://storage.googleapis.com/minikube/releases/v0.20.0/minikube-linux-amd64 -o usr/local/bin/minikube
  - chmod +x /usr/local/bin/minikube
  - minikube start --vm-driver=none --kubernetes-version v1.7.0
