default:
 default:
 client: localhost
 numcpus: 2
 diskthin: true
 memory: 512
 disks:
  - size: 10
 protocol: ssh
 cloudinit: true
 reserveip: false
 nets:
  - default

localhost:
 host: 127.0.0.1
 pool: default

