centos:
 template: CentOS-7-x86_64-GenericCloud.qcow2
 numcpus: 2
 memory: 1024
 nets: 
  - default
 pool: default
 cmds: 
  - echo magico | passwd --stdin root
  - yum -y install nmap

centos27:
 template: CentOS-7-x86_64-GenericCloud.qcow2
 numcpus: 2
 nets: 
  - name: localnet
    mask: 255.255.255.0
    gateway: 192.168.0.254
  - private
 pool: default
 disks:
  - size: 10
  - size: 2
    thin: false
 keys:
  - ssh-rsa XXX
  - ssh-rsa YYY
