parameters:
 domain: karmalabs.com
 template: CentOS-7-x86_64-GenericCloud.qcow2
 nfs: false
 sdn: flannel
 version: 1.11.0
 multus: false
 skydive: false

kubernetes:
 template: [[ template ]]
 numcpus: 2
 memory: 8192
 reservedns: true
 domain: [[ domain ]]
 nets:
  - default
 disks:
  - size: 50
 pool: default
 files:
  - skydive.yml
  - path: /etc/yum.repos.d/kubernetes.repo
    origin: kubernetes.repo
[% if nfs %]
  - nfs.yml
  - nfs.sh
[% endif %]
[% if multus %]
  - multus.yml
  - cni-plugins.yml
  - l2-bridge.yml
[% endif %]
 scripts: 
[% if 'xenial' in template or 'yaketty' in template or 'zesty' in template or 'artful' in template or 'bionic' in template or 'cosmic' in template %]
  - pre_ubuntu.sh
[% else %]
  - pre.sh
[% endif %]
  - master.sh
  - dashboard.sh
[% if multus %]
  - multus.sh
[% endif %]
[% if skydive %]
  - skydive.sh
[% endif %]
