parameters:
 domain: karmalabs.com
 template: CentOS-7-x86_64-GenericCloud.qcow2
 nfs: false
 sdn: flannel
 version: 1.10.5

kubernetes:
 template: [[ template ]]
 numcpus: 2
 memory: 8192
 reservedns: true
 domain: [[ domain ]]
 nets:
  - default
 disks:
  - size: 50
 pool: default
 files:
  - path: /etc/yum.repos.d/kubernetes.repo
    origin: kubernetes.repo
  - path: /root/kube-flannel.yml
    origin: kube-flannel.yml
  - path: /root/kube-flannel-rbac.yml
    origin: kube-flannel-rbac.yml
[% if nfs %]
  - path: /root/nfs.yml
    origin: nfs.yml
  - path: /root/nfs.sh
    origin: nfs.sh
[% endif %]
 scripts: 
  - pre.sh
  - master.sh
  - dashboard.sh
