parameters:
 domain: karmalabs.com
 template: CentOS-7-x86_64-GenericCloud.qcow2
 nfs: false
 sdn: flannel
 version: 1.11.0
 multus: false

kubernetes:
 template: [[ template ]]
 numcpus: 2
 memory: 8192
 reservedns: true
 domain: [[ domain ]]
 nets:
  - default
 disks:
  - size: 50
 pool: default
 files:
  - path: /etc/yum.repos.d/kubernetes.repo
    origin: kubernetes.repo
[% if nfs %]
  - path: /root/nfs.yml
    origin: nfs.yml
  - path: /root/nfs.sh
    origin: nfs.sh
[% endif %]
[% if multus %]
  - path: /root/multus.yml
    origin: multus.yml
  - path: /root/cni-plugins.yml
    origin: cni-plugins.yml
  - path: /root/l2-bridge.yml
    origin: l2-bridge.yml
[% endif %]
 scripts: 
[% if 'xenial' in template or 'yaketty' in template or 'zesty' in template or 'artful' in template or 'bionic' in template or 'cosmic' in template %]
  - pre_ubuntu.sh
[% else %]
  - pre.sh
[% endif %]
  - master.sh
  - dashboard.sh
[% if multus %]
  - multus.sh
[% endif %]
