parameters:
 baseplan: kcli_plan.yml
 kubevirt_version: v0.10.0
 cdi: true
 cdi_version: v1.3.0
 ui: true
 ui_version: v1.3-9

kubevirt:
 template: {{ template }}
 numcpus: 2
 memory: 8192
 reservedns: true
 domain: {{ domain }}
 nets:
  - default
 disks:
  - size: 50
 pool: default
 files:
  - path: /etc/yum.repos.d/kubernetes.repo
    origin: kubernetes.repo
  - kubevirt_ui.yml
  - cdi-controller.yaml
{% if nfs %}
  - path: /root/nfs.yml
    origin: nfs.yml
  - path: /root/nfs.sh
    origin: nfs.sh
{% endif %}
 scripts: 
  - pre.sh
  - master.sh
  - dashboard.sh
  - kubevirt.sh
{% if cdi %}
  - cdi.sh
{% endif %}
{% if ui %}
  - kubevirt_ui.sh
{% endif %}
