apiVersion: v1
kind: Namespace
metadata:
  name: kcli-infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcli-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: kcli-infra
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcli-controller
  namespace: kcli-infra
  labels:
    app: kcli-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcli-controller
  template:
    metadata:
      labels:
        app: kcli-controller
    spec:
      containers:
      - name: kcli-controller
        image: karmab/kcli-controller:latest
        volumeMounts:
        - mountPath: /root/.kcli
          name: kcli-conf
        - mountPath: /root/.ssh
          name: kcli-ssh
      volumes:
      - configMap:
          defaultMode: 0700
          name: kcli-conf
        name: kcli-conf
      - configMap:
          defaultMode: 0700
          name: kcli-ssh
        name: kcli-ssh
