apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kcli-workdir
  namespace: kcli-infra
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcli-controller
  namespace: kcli-infra
  labels:
    app: kcli-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcli-controller
  template:
    metadata:
      labels:
        app: kcli-controller
    spec:
      containers:
      - name: kcli-controller
        image: karmab/kcli-controller:latest
        volumeMounts:
        - name: kcli-conf
          mountPath: /root/.kcli
        - name: kcli-ssh
          mountPath: /root/.ssh
        - name: kcli-workdir
          mountPath: /workdir
      volumes:
      - name: kcli-conf
        configMap:
          defaultMode: 0700
      - name: kcli-ssh
        configMap:
          defaultMode: 0700
      - name: kcli-workdir
        persistentVolumeClaim:
          claimName: kcli-workdir
