apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "{{ localstorage_name }}"
  namespace: "local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
{%- if localstorage_nodes %}
{%- for node in localstorage_nodes %}
          - {{ node }}
{%- endfor %}
{%- else %}
{%- for num in range(masters) %}
          - {{ cluster }}.master-{{ num }}.{{ cluster }}.{{ domain }}
{%- endfor %}
{%- endif %}
  storageClassDevices:
    - storageClassName: {{ localstorage_storageclass }}
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
{%- for disk in localstorage_disks %}
      - /dev/{{ disk | replace('/dev/', '') }}
{%- endfor %}
