apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kcli-pool
  namespace: metallb-system
spec:
  protocol: {{ 'bgp' if metallb_bgp else 'layer2' }}
  autoAssign: {{ metallb_autoassign }}
  addresses:
{% for metallb_range in metallb_ranges %}
  - {{ metallb_range }}
{% endfor %}
