name: CI
on: [push, pull_request]

env:
 QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
 QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
 PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
 PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
 DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
 DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
 CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

jobs:

  run-workflow:
    name: Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo .github/prep.sh
        shell: bash
      - name: Lint Code
        run: .github/linting.sh
        shell: bash
      - name: Test code
        run: .github/testing.sh
        shell: bash
      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: Release Artifacts
        run: .github/release.sh
        shell: bash
      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: Build And Push Container
        run: .github/container.sh
        shell: bash
