name: ci
on: push

env:
 QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
 QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
 PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
 PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
 DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
 DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
 CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

jobs:

  prepare-environment:
    name: Preparation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Dependencies
        run: sudo .github/prep.sh
        shell: bash
      - name: Setup Hypervisor
        run: sudo .github/setup_hypervisor.sh
        shell: bash
      - name: Lint Code
        run: .github/linting.sh
        shell: bash
      - name: Build Container
        run: .github/build.sh
        shell: bash
      - name: Test code
        run: .github/build.sh
        shell: bash
      - name: Release
        run: .github/release.sh
        shell: bash
        # if: success() && github.event_name != 'pull_request'
