name: HYPERSHIFT-ASSISTED-NIGHTLY-CI
on:
  schedule:
    - cron: '39 01 * * *'

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 CLUSTER: ci-hypershift-assisted
 PULLSECRET: /root/openshift_pull.json
 KUBECONFIG: /root/.kcli/clusters/ci-sno/auth/kubeconfig
 PARAMFILE: openshift-ci-paramfiles/hypershift_assisted.yml

jobs:
 requirements:
   if: github.repository == 'karmab/kcli'
   runs-on: karim03
   steps:
    - uses: actions/checkout@v2
    - run: git pull origin ${GITHUB_REF##*/}
    - name: Install kcli
      run: |
        curl https://raw.githubusercontent.com/karmab/kcli/main/install.sh | bash
        kcli create sushy-service
    - name: Delete old install
      run: |
        kcli delete cluster --yes $CLUSTER || true
        kcli delete plan --yes $CLUSTER-vms || true

 deploy-baremetal-like-vms:
   needs: requirements
   runs-on: karim03
   steps:
   - name: Deploy Baremetal like vm
     run: |
       kcli create vm -P uefi=true -P start=false -P memory=20480 -P numcpus=16 -P disks=['{"size": 200, "interface": "sata"}'] -P nets=['{"name": "baremetalfake", "mac": "aa:aa:aa:bb:bb:80"}'] -P plan=$CLUSTER-vms -P user=core -c 2 $CLUSTER

 deploy-hypershift:
   needs: deploy-baremetal-like-vms
   runs-on: karim03
   steps:
   - name: Deploy HYPERSHIFT ASSISTED
     run: |
       kcli create cluster hypershift --pf $PARAMFILE -P pull_secret=$PULLSECRET $CLUSTER --force

 clean-up:
   needs: deploy-hypershift
   runs-on: karim03
   steps:
   - name: Clean everything after success
     run: |
       kcli delete cluster --yes $CLUSTER
       kcli delete plan --yes $CLUSTER-vms
