name: HYPERSHIFT-NIGHTLY-CI

on:
   schedule:
    - cron: '31 22 * * *'

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 PLAN: ci-hypershift
 PULLSECRET: /root/openshift_pull.json
 KUBECONFIG: /root/.kcli/clusters/ci-sno/auth/kubeconfig
 PARAMFILE: openshift-ci-paramfiles/hypershift.yml

jobs:
    requirements:
      if: github.repository == 'karmab/kcli'
      runs-on: karim03
      steps:
       - uses: actions/checkout@v2
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/main/install.sh | bash

    deploy-hypershift:
      needs: requirements
      runs-on: karim03
      steps:
      - name: Deploy hypershift cluster
        run: kcli create cluster hypershift --pf $PARAMFILE -P pull_secret=$PULLSECRET $PLAN --force
      - name: Clean everything
        if: always()
        run: kcli delete plan --yes $PLAN
