name: HYPERSHIFT-ASSISTED-CI
on:
  workflow_dispatch:
    inputs:
      CLUSTER:
        description: 'Cluster'
        required: true
        default: ci-hypershift-assisted
      PARAMFILE:
        description: 'paramfile'
        required: false
        default: openshift-ci-paramfiles/hypershift_assisted.yml
      EXTRAPARAMS:
        description: 'Extra params'
        default: ''
      PULLSECRET:
        description: 'Pull Secret'
        required: false
        default: /root/openshift_pull.json
      VERSION:
        description: 'version'
        required: false
        default: stable
      TAG:
        description: 'tag'
        required: false
        default: "4.13"

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 KUBECONFIG: /root/.kcli/clusters/ci-libvirt/auth/kubeconfig
 CLUSTER: ${{github.event.inputs.CLUSTER}}
 INPUTFILE: ${{github.event.inputs.INPUTFILE}}
 PARAMFILE: ${{github.event.inputs.PARAMFILE}}
 EXTRAPARAMS: ${{github.event.inputs.EXTRAPARAMS}}
 PULLSECRET: ${{github.event.inputs.PULLSECRET}}
 VERSION: ${{github.event.inputs.VERSION}}
 TAG: ${{github.event.inputs.TAG}}

jobs:
    requirements:
      runs-on: libvirt
      steps:
       - uses: actions/checkout@v2
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/main/install.sh | bash
           kcli create sushy-service
       - name: Delete old install
         run: |
           kcli delete cluster --yes $CLUSTER || true
           kcli delete plan --yes $CLUSTER-vms || true

    deploy-baremetal-like-vms:
      needs: requirements
      runs-on: libvirt
      steps:
      - name: Deploy Baremetal like vms
        run: |
          kcli -C local create vm -P uefi=true -P start=false -P memory=20480 -P numcpus=16 -P disks=['{"size": 200, "interface": "sata"}'] -P nets=['{"name": "default", "mac": "aa:aa:aa:bb:bb:80"}'] -P plan=$CLUSTER-vms -P user=core -c 3 $CLUSTER

    deploy-hypershift:
      needs: deploy-baremetal-like-vms
      runs-on: libvirt
      steps:
      - name: Deploy HYPERSHIFT ASSISTED
        run: |
          kcli create cluster hypershift --paramfile $PARAMFILE -P pull_secret=$PULLSECRET -P version=$VERSION -P tag="$TAG" $EXTRAPARAMS $CLUSTER
