name: HYPERSHIFT-ASSISTED-NIGHTLY-CI
on:
  schedule:
    - cron: '39 01 * * *'

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 CLUSTER: ci-hypershift-assisted
 PULLSECRET: /root/openshift_pull.json
 KUBECONFIG: /root/.kcli/clusters/ci-sno/auth/kubeconfig
 PARAMFILE: openshift-ci-paramfiles/hypershift_assisted.yml

jobs:
 requirements:
   if: github.repository == 'karmab/kcli'
   runs-on: u08
   steps:
    - uses: actions/checkout@v2
    - run: git pull origin ${GITHUB_REF##*/}
    - name: Install kcli
      run: |
        curl https://raw.githubusercontent.com/karmab/kcli/main/install.sh | bash
        kcli create sushy-service
    - name: Delete old install
      run: |
        kcli delete cluster --yes $CLUSTER || true

 deploy-hypershift:
   runs-on: u08
   steps:
   - name: Deploy HYPERSHIFT ASSISTED
     run: |
       kcli create cluster hypershift --pf $PARAMFILE -P pull_secret=$PULLSECRET $CLUSTER --force

 clean-up:
   needs: deploy-hypershift
   runs-on: u08
   steps:
   - name: Clean everything after success
     run: |
       kcli delete cluster --yes $CLUSTER
