name: OPENSHIFT-NIGHTLY-CI
on:
  schedule:
    - cron: '15 23 * * *'

env:
 HOME: /root
 PLAN: ci
 PULLSECRET: /root/openshift_pull.json
 VERSION: stable
 TAG: 4.9

jobs:
  deploy-openshift:
    strategy:
      fail-fast: false
      matrix:
        provider: [libvirt, kubevirt, openstack, ovirt]
    runs-on: ${{ matrix.provider }}
    steps:
     - uses: actions/checkout@v2
     - run: git pull origin ${GITHUB_REF##*/}
     - name: Install kcli
       run: curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
     - name: Delete old install
       run: kcli delete cluster --yes ${{env.PLAN}}-${{ matrix.provider }}
     - name: Deploy Openshift on ${{ matrix.provider }}
       run: kcli create cluster openshift --paramfile openshift-ci-paramfiles/${{ matrix.provider }}.yml -P pull_secret='${{env.PULLSECRET}}' -P version='${{env.VERSION}}' -P tag='${{env.TAG}}' ${{env.PLAN}}-${{ matrix.provider }}
