name: SNAPSHOT-ARM-DAILY
on:
  schedule:
    - cron: '39 19 * * *'

env:
 QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
 QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
 PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
 PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
 CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
 COPR_BASE64: ${{ secrets.COPR_BASE64 }}
 PYTHONUNBUFFERED: true

jobs:

  run-workflow:
    name: Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo .github/prep.sh
      - name: Lint Code
        run: .github/linting.sh
      - name: Test code
        run: .github/testing.sh
      - if: github.ref == 'refs/heads/main' && github.repository_owner == 'karmab'
        name: Snapshot container
        run: |
          export TAG=arm64
          .github/container_snapshot.sh
